export const GET_RN_OPEN_REPO = 'GET_RN_OPEN_REPO';
export const RECEIVE_RN_OPEN_REPO = 'RECEIVE_RN_OPEN_REPO';
export const PULL_REFRESH_RN_OPEN_REPO = 'PULL_REFRESH_RN_OPEN_REPO';
export const SEARCH_REPO = 'SEARCH_REPO';
export const SEARCH_REPO_RESULT= 'SEARCH_REPO_RESULT';